Repository Tech-Titans-TM/tick-flow-app, pull requests merged in 2025-04, with the labels that each got.

#4 feat: and and view tasks
  src/App.jsx
  src/components/task-management/add-edit-tasks.css
  src/components/task-management/add-edit-tasks.jsx
  src/pages/task-management/add-edit-task-page.jsx
  src/pages/task-management/task-management-page.jsx
Labels: Work in progress

#5 feat: list all the tasks created and new tab layout to filter the tasks
  src/components/task-management/add-edit-tasks.jsx
  src/pages/task-management/task-management-page.jsx
Labels: dev-done, ready-for-review

#10 feat: functionality to update or delete the tasks
  src/components/task-management/add-edit-tasks.jsx
  src/pages/task-management/task-management-page.jsx
  src/utils/api/tasks/tasks.service.js
Labels: dev-done, ready-for-review

#9 Feature/frontend setup/visal
  src/App.jsx
  src/components/side-bar/side-bar.jsx
  src/contexts/authContext.jsx
  src/pages/settings/settings.jsx
  src/utils/axiosInstance.jsx
  src/utils/protectedRoute.jsx
Labels: dev-done, ready-for-review

#11 feat: enhancements in manage tasks
  src/components/task-management/add-edit-tasks.jsx
  src/pages/task-management/task-management-page.jsx
Labels: enhancement, dev-done, ready-for-review

#13 fix: reverse: revert-11-feature/manage-tasks-enhancements/himashana from main (Rev_Commit_SHA: 97c6b9a9d971fbcec4424b48a308c01587eb4de1)
  src/components/task-management/add-edit-tasks.jsx
  src/pages/task-management/task-management-page.jsx
Labels: dev-done, ready-for-review, revert

#14 Feature/frontend setup/visal
  package-lock.json
  package.json
  src/pages/home/home.jsx
  src/pages/settings/settings.jsx
Labels: dev-done, ready-for-review
